-- Intentionally empty.
--
-- Kickstart's version of this file auto-loaded every sibling `.lua` file by
-- iterating the directory. That is unsafe with `vim.pack`, whose `add` is
-- imperative and order-dependent -- `vim.fs.dir` gives no ordering guarantee,
-- so build hooks could register after the installs they are meant to handle.
--
-- Load order is explicit in `lua/custom/init.lua` instead. Register new plugin
-- modules there.
